telegram:
  bot:
    token: ${BOT_TOKEN}
    url: ${BOT_URL}
    path: ${BOT_PATH}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_LOGIN}
    password: ${RABBITMQ_PASSWORD}
server:
  port: 8083
  ssl:
    enabled: false