spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5436/telegram
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    generate-ddl: true


telegram:
  bot:
    token: ${TOKEN}
  service:
    mail:
      uri: http://127.0.0.1:8085/mail/send
    file-info:
      uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file-storage:
      uri: https://api.telegram.org/file/bot{token}/{filePath}

salt: ${SALT}
link:
  address: "127.0.0.1:8086"
server:
  port: ${PORT:8080}