spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: be46a388
  datasource:
    url: jdbc:postgresql://localhost:5436/telegram
    password: password
    username: user
  jpa:
    generate-ddl: true
server:
  port: 8083

telegram:
  bot:
    token: "6687504052:AAHTO74sbMK2sje-C5bIMhYxHZa5Ru-7XXY"
  service:
    file-info:
      uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file-storage:
      uri: https://api.telegram.org/file/bot{token}/{filePath}

salt: "Pq12GSnZ5CwkrmutojxQbM13cRi8speFya7600NUYKgThHAWJIfLdD9V4XEvzB"
link:
  address: "127.0.0.1:8086"