spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/telegram
    password: password
    username: user
  jpa:
    generate-ddl: true
server:
  port: 8086

salt: "Pq12GSnZ5CwkrmutojxQbM13cRi8speFya7600NUYKgThHAWJIfLdD9V4XEvzB"
